#!/usr/bin/env bash

echo "Start checking"

PID=$1
MYHOST=`hostname -s`
while :
do
    if [[ ! -e "/proc/${PID}" ]];then
        echo "Done"
        exit 0
    fi

    echo `date` "    PID ${PID} still lives"
    sleep 10
done


