#!/bin/env zsh

echo "Start checking"

PID=$1
MYHOST=`hostname -s`
while :
do
    if [[ `ps -p ${PID} | wc -l` -ne 2 ]];then
        exit 0
    fi

    echo -n "\r" `date` "    PID ${PID} still lives"
    sleep 20
done


